library(Seurat)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(patchwork)
library(dplyr)
library(abind)
library(ACAT)
library(tibble)


#require objects generated by "Preprocessing.R" 
#require Antibody_stats_HIV_DNApos.csv
#require Antibody_stats_HIV_RNApos.csv

#Fig. 5A
Antibody_stats_HIV_DNApos <- data.frame(antibody = Viremic_HIV_DNA_pos[["Antibody"]]@data)
Antibody_stats_HIV_DNApos$mean <- rowMeans(Antibody_stats_HIV_DNApos, na.rm=TRUE)
Antibody_stats_HIV_DNApos$sd <- apply(Antibody_stats_HIV_DNApos, 1, sd, na.rm=TRUE)
Antibody_stats_HIV_DNApos$names <- rownames(Antibody_stats_HIV_DNApos)
Antibody_stats_HIV_DNApos <- Antibody_stats_HIV_DNApos[,c(234, 235, 236)]
#match  each row of protein rows with its specific isotype control (using e.g., excel; required columns are protein and standard deviations and mean expressions) then compute 2 sample z score

Antibody_stats_HIV_DNApos$X2.sample.z.score <- (Antibody_stats_HIV_DNApos$mean - 
                                                  Antibody_stats_HIV_DNApos$isotype_mean)/sqrt(Antibody_stats_HIV_DNApos$sd^2/233 +
                                                                                                 Antibody_stats_HIV_DNApos$isotype_sd^2/233)
Antibody_stats_HIV_DNApos <- Antibody_stats_HIV_DNApos[Antibody_stats_HIV_DNApos$X2.sample.z.score > 2,]
rownames(Antibody_stats_HIV_DNApos) <- Antibody_stats_HIV_DNApos$names
#see Antibody_stats_HIV_DNApos.csv

DefaultAssay(Viremic) <- 'CITE_dsb'; Idents(Viremic) <- "HIV_RNA_DNA2"

DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg <- vector(mode = "list", length = 1000)
DEA.downsample.HIV_DNA_Pos_vs_Neg_bootstrap <- vector(mode = "list", length = 1000)
for(i in 1:length(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg)){
  DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- FindMarkers(object = Viremic.cite, ident.1 = "DNA positive", ident.2 = "negative", min.pct = 0.05,
                                                                max.cells.per.ident = 233, random.seed = i, features = rownames(Antibody_stats_HIV_DNApos), pseudocount.use = 1)
  DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]]$BH <- p.adjust(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]]$p_val, 
                                                                method = "BH", n = nrow(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]]))
  merged_ID <- unique(c(rownames(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]])))
  DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]][merged_ID,]
  DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]][order(rownames(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]])),]
  DEA.downsample.HIV_DNA_Pos_vs_Neg_bootstrap[[i]] <- data.frame(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]][,1])
  downsample.HIV_RNA_Pos_vs_Neg_bootstrap1 <- t(matrix(unlist(DEA.downsample.HIV_DNA_Pos_vs_Neg_bootstrap), nrow = length(merged_ID)))
  Cauchy <- ACAT(matrix(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1, ncol = ncol(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1)))
  matrix <- cbind(DEA.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[1]], Cauchy)
  DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- matrix[, -c(1,5,6)]
}
DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH <- p.adjust(DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$Cauchy, method = "BH", n = nrow(DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap))
DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$gene <- rownames(DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap)

DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap[!(DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$avg_log2FC > 0 &
                                                                                         DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$pct.1 < DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$pct.2),]
DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap[!(DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$avg_log2FC < 0 &
                                                                                         DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$pct.1 > DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$pct.2),]


options(ggrepel.max.overlaps = 30)
mycolors <- c("blue", "red", "grey")
names(mycolors) <- c("downregulated", "upregulated", "NS")

DE <- DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap
DE$genesymbol <- DE$gene
DE$diffexpressed[DE$avg_log2FC > 0 & DE$BH < 0.05] <- "upregulated"
DE$diffexpressed[DE$avg_log2FC < 0  & DE$BH < 0.05] <- "downregulated"
DE$diffexpressed[DE$BH > 0.05] <- "NS"
DE$delabel <- NA
DE$delabel[DE$diffexpressed != "NS"] <- DE$genesymbol[DE$diffexpressed != "NS"]
DE.DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- DE

ggplot(data = DE.DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap, aes(x = DE.DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$avg_log2FC, 
                                                               y = -log10(DE.DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH), 
                                                               col = diffexpressed, label = delabel)) + geom_point() + theme_minimal() + scale_color_manual(
                                                               values = mycolors) + geom_text_repel() + xlim(-0.6,0.6) + ylim(0,5)

#Fig. 5B
Antibody_stats_HIV_RNApos <- data.frame(antibody = HIV_RNApos[["Antibody"]]@data)
Antibody_stats_HIV_RNApos$mean <- rowMeans(Antibody_stats_HIV_RNApos, na.rm=TRUE)
Antibody_stats_HIV_RNApos$sd <- apply(Antibody_stats_HIV_RNApos, 1, sd, na.rm=TRUE)
Antibody_stats_HIV_RNApos$names <- rownames(Antibody_stats_HIV_RNApos)
Antibody_stats_HIV_RNApos <- Antibody_stats_HIV_RNApos[,c(257, 258, 259)]
#match  each row of protein rows with its specific isotype control (using e.g., excel; required columns are protein and standard deviations and mean expressions) then compute 2 sample z score

Antibody_stats_HIV_RNApos$X2.sample.z.score <- (Antibody_stats_HIV_RNApos$mean - 
                                                  Antibody_stats_HIV_RNApos$isotype_mean)/sqrt(Antibody_stats_HIV_RNApos$sd^2/256 +
                                                                                                 Antibody_stats_HIV_RNApos$isotype_sd^2/256)
Antibody_stats_HIV_RNApos <- Antibody_stats_HIV_RNApos[Antibody_stats_HIV_RNApos$X2.sample.z.score > 2,]
rownames(Antibody_stats_HIV_RNApos) <- Antibody_stats_HIV_RNApos$names
#see Antibody_stats_HIV_RNApos.csv

DefaultAssay(Viremic.cite) <- 'CITE_dsb'; Idents(Viremic.cite) <- "HIV_RNA_DNA2"

DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg <- vector(mode = "list", length = 1000)
DEA.downsample.HIV_RNA_Pos_vs_Neg_bootstrap <- vector(mode = "list", length = 1000)
for(i in 1:length(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg)){
  DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- FindMarkers(object = Viremic.cite, ident.1 = "RNA and double positive", ident.2 = "negative", min.pct = 0.05,
                                                                max.cells.per.ident = 256, random.seed = i, features = rownames(Antibody_stats_HIV_RNApos),pseudocount.use = 1)
  DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]]$BH <- p.adjust(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]]$p_val, 
                                                                method = "BH", n = nrow(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]]))
  merged_ID <- unique(c(rownames(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]])))
  DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]][merged_ID,]
  DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]][order(rownames(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]])),]
  DEA.downsample.HIV_RNA_Pos_vs_Neg_bootstrap[[i]] <- data.frame(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]][,1])
  downsample.HIV_RNA_Pos_vs_Neg_bootstrap1 <- t(matrix(unlist(DEA.downsample.HIV_RNA_Pos_vs_Neg_bootstrap), nrow = length(merged_ID)))
  Cauchy <- ACAT(matrix(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1, ncol = ncol(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1)))
  matrix <- cbind(DEA.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[1]], Cauchy)
  DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- matrix[, -c(1,5,6)]
}
DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH <- p.adjust(DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$Cauchy, method = "BH", n = nrow(DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap))
DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$gene <- rownames(DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap)

DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap[!(DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_log2FC > 0 &
                                                                                         DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$pct.1 < DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$pct.2),]
DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap[!(DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_log2FC < 0 &
                                                                                         DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$pct.1 > DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$pct.2),]

options(ggrepel.max.overlaps = 30)
mycolors <- c("blue", "red", "grey")
names(mycolors) <- c("downregulated", "upregulated", "NS")

DE <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap
DE$genesymbol <- DE$gene
DE$diffexpressed[DE$avg_log2FC > 0 & DE$BH < 0.05] <- "upregulated"
DE$diffexpressed[DE$avg_log2FC < 0  & DE$BH < 0.05] <- "downregulated"
DE$diffexpressed[DE$BH > 0.05] <- "NS"
DE$delabel <- NA
DE$delabel[DE$diffexpressed != "NS"] <- DE$genesymbol[DE$diffexpressed != "NS"]
DE.DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- DE

ggplot(data = DE.DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap, aes(x = DE.DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_log2FC, 
                                                               y = -log10(DE.DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH), 
                                                               col = diffexpressed, label = delabel)) + geom_point() + theme_minimal() + scale_color_manual(
                                                               values = mycolors) + geom_text_repel() + xlim(-1,1)

#Fig. 5C
DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap.sig <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap[DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH < 0.05,]
DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap.sig <- DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap[DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH < 0.05,]

DEA.Viremic.HIV_RNA_DNA_pos_vs_neg_bootstrap <- c(DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap.sig$gene, 
                                                         DEA.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap.sig$gene)
DEA.Viremic.HIV_RNA_DNA_pos_vs_neg_bootstrap.unique <- DEA.Viremic.HIV_RNA_DNA_pos_vs_neg_bootstrap[!duplicated(DEA.Viremic.HIV_RNA_DNA_pos_vs_neg_bootstrap)]


avg_exp.Viremic <- AverageExpression(Viremic, return.seurat = T, group.by = 'HIV_RNA_DNA2')
avg_exp.Viremic$orig.ident <- colnames(avg_exp.Viremic)
DefaultAssay(avg_exp.Viremic) <- "CITE_dsb"; Idents(avg_exp.Viremic) <- "orig.ident"
avg_exp.Viremic <- ScaleData(avg_exp.Viremic)
Idents(avg_exp.Viremic) <- factor(Idents(avg_exp.Viremic), levels = c("RNA and double positive", "DNA positive", "negative"))

DoHeatmap(object = avg_exp.Viremic, features = DEA.Viremic.HIV_RNA_DNA_pos_vs_neg_bootstrap.unique, group.bar.height = 0.02, size = 4, angle = 0, 
          draw.lines = FALSE) + scale_fill_gradientn(colors = c("blue", "white", "red"))

#Fig. 5D
DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap[DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_log2FC > 0,]
DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg[DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$BH < 0.05,]

DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg <- DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg[
                                    DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$gene %in% c(
                                    "CD2-TotalA","CD11a-TotalA","CD150-TotalA","CD161-TotalA", "CD195-TotalA",  "CD45-TotalA", "CD49d-TotalA"),]

DefaultAssay(Viremic) <- "Antibody"; DefaultAssay(Suppressed) <- "Antibody"
Idents(Viremic) <- "HIV_RNA_DNA2"; Idents(Suppressed) <- "HIV_RNA_DNA2"
Idents(Viremic) <- factor(Idents(Viremic), levels = c("DNA positive", "RNA and double positive", "negative"))
Idents(Suppressed) <- factor(Idents(Suppressed), levels = c("DNA positive", "RNA and double positive", "negative"))

DotPlot(Viremic.cite, features = DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$gene, dot.scale = 20, scale.min = 40, scale.max = 100, cols = c("grey","blue")) + scale_y_discrete(limits = rev)
DotPlot(Suppressed, features = DEA.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$gene, dot.scale = 20, scale.min = 40, scale.max = 100, cols = c("grey","blue")) + scale_y_discrete(limits = rev) 

#Fig. 5F
DefaultAssay(Viremic) <- "CITE_dsb"; Idents(Viremic) <- "HIV_RNA_DNA2"
RidgePlot(Viremic, features = c("CD195-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD196-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD183-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD161-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD119-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')

#Fig. 5G
DefaultAssay(Viremic) <- "CITE_dsb"; Idents(Viremic) <- "HIV_RNA_DNA2"
RidgePlot(Viremic, features = c("CD49d-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD44-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD11a-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')

#Fig. 5F
DefaultAssay(Viremic) <- "CITE_dsb"; Idents(Viremic) <- "HIV_RNA_DNA2"
RidgePlot(Viremic, features = c("CD81-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD38-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD278-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD2-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD150-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD352-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("HLA-A-B-C-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("HLA-DR-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("HLA-DR-DP-DQ-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
RidgePlot(Viremic, features = c("CD45-TotalA"), idents = factor(Idents(Viremic.cite), levels = c("RNA and double positive", "DNA positive", "negative")), sort = 'increasing')
