library(Seurat)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(patchwork)
library(dplyr)
library(abind)
library(ACAT)
library(WGCNA)
library(flashClust)
library(Hmisc)
library(qlcMatrix)
library(reshape2)
library(scales)
library(Matrix)
library(fgsea)
library(msigdbr)
library(tibble)
library(topGO)
library(org.Hs.eg.db)

#require objects generated by "Preprocessing.R" 
#require processing by "build WGCNA.R"
#require processing by "build GSEA.R"

Viremic$HIV_RNA_DNA2 <- Viremic$HIV_RNA_DNA
Idents(Viremic) <- "HIV_RNA_DNA2"
Viremic <-RenameIdents(Viremic, 'positive_positive' = 'HIV RNA and double positive', 
                       'positive_negative' = 'HIV RNA and double positive', 'negative_positive' = 'HIV DNA positive',
                       'negative_negative' = 'HIV negative') 
Viremic$HIV_RNA_DNA2 <- Idents(Viremic)

Suppressed$HIV_RNA_DNA2 <- Suppressed$HIV_RNA_DNA
Idents(Suppressed) <- "HIV_RNA_DNA2"
Suppressed <-RenameIdents(Suppressed, 'positive_positive' = 'HIV RNA and double positive', 
                       'positive_negative' = 'HIV RNA and double positive', 'negative_positive' = 'HIV DNA positive',
                       'negative_negative' = 'HIV negative') 
Suppressed$HIV_RNA_DNA2 <- Idents(Suppressed)

#Fig. 4A
DefaultAssay(Viremic) <- 'RNA'; Idents(Viremic) <- "HIV_RNA_DNA2"

DEG.downsample.HIV_DNA_Pos_vs_Neg <- vector(mode = "list", length = 1000)
DEG.downsample.HIV_DNA_Pos_vs_Neg_bootstrap <- vector(mode = "list", length = 1000)
for(i in 1:length(DEG.downsample.HIV_DNA_Pos_vs_Neg)){
  DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- FindMarkers(object = Viremic, ident.1 = "HIV DNA positive", ident.2 = "HIV negative", min.pct = 0.15, max.cells.per.ident = 233, random.seed = i,
                                                        only.pos = FALSE, test.use = 'wilcox',pseudocount.use = 1)
  DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]]$BH <- p.adjust(DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]]$p_val, 
                                                        method = "BH", n = nrow(DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]]))
  merged_ID <- unique(c(rownames(DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]])))
  DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]][merged_ID,]
  DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]][order(rownames(DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]])),]
  DEG.downsample.HIV_DNA_Pos_vs_Neg_bootstrap[[i]] <- data.frame(DEG.downsample.HIV_DNA_Pos_vs_Neg[[i]][,1])
  downsample.HIV_DNA_Pos_vs_Neg_bootstrap1 <- t(matrix(unlist(DEG.downsample.HIV_DNA_Pos_vs_Neg_bootstrap), nrow = length(merged_ID)))
  Cauchy <- ACAT(matrix(downsample.HIV_DNA_Pos_vs_Neg_bootstrap1, ncol = ncol(downsample.HIV_DNA_Pos_vs_Neg_bootstrap1)))
  matrix <- cbind(DEG.downsample.HIV_DNA_Pos_vs_Neg[[1]], Cauchy)
  DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- matrix[, -c(1,5,6)]
}
DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH <- p.adjust(DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$Cauchy, method = "BH", n = nrow(DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap))

options(ggrepel.max.overlaps = 30)
mycolors <- c("blue", "red", "grey")
names(mycolors) <- c("downregulated", "upregulated", "NS")

DE <- DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap
DE$genesymbol <- rownames(DE)
DE$diffexpressed[DE$avg_log2FC > 0 & DE$BH < 0.05] <- "upregulated"
DE$diffexpressed[DE$avg_log2FC < 0  & DE$BH < 0.05] <- "downregulated"
DE$diffexpressed[DE$BH > 0.05] <- "NS"
DE$delabel <- NA
DE$delabel[DE$diffexpressed != "NS"] <- DE$genesymbol[DE$diffexpressed != "NS"]
DE.DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- DE

ggplot(data = DE.DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap, aes(x = DE.DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$avg_log2FC, 
                                                               y = -log10(DE.DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH), 
                                                               col = diffexpressed, label = delabel)) + geom_point() + theme_minimal() + scale_color_manual(
                                                               values = mycolors) + geom_text_repel() 

#Fig. 4B
DefaultAssay(Viremic) <- 'RNA'; Idents(Viremic) <- "HIV_RNA_DNA2"

DEG.downsample.HIV_RNA_Pos_vs_Neg <- vector(mode = "list", length = 1000)
DEG.downsample.HIV_RNA_Pos_vs_Neg_bootstrap <- vector(mode = "list", length = 1000)
for(i in 1:length(DEG.downsample.HIV_RNA_Pos_vs_Neg)){
  DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- FindMarkers(object = Viremic, ident.1 = "HIV RNA and double positive", ident.2 = "HIV negative", min.pct = 0.15, max.cells.per.ident = 256, random.seed = i,
                                                        only.pos = FALSE, test.use = 'wilcox', pseudocount.use = 1)
  DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]]$BH <- p.adjust(DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]]$p_val, 
                                                        method = "BH", n = nrow(DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]]))
  merged_ID <- unique(c(rownames(DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]])))
  DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]][merged_ID,]
  DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]][order(rownames(DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]])),]
  DEG.downsample.HIV_RNA_Pos_vs_Neg_bootstrap[[i]] <- data.frame(DEG.downsample.HIV_RNA_Pos_vs_Neg[[i]][,1])
  downsample.HIV_RNA_Pos_vs_Neg_bootstrap1 <- t(matrix(unlist(DEG.downsample.HIV_RNA_Pos_vs_Neg_bootstrap), nrow = length(merged_ID)))
  Cauchy <- ACAT(matrix(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1, ncol = ncol(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1)))
  matrix <- cbind(DEG.downsample.HIV_RNA_Pos_vs_Neg[[1]], Cauchy)
  DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- matrix[, -c(1,5,6)]
}
DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH <- p.adjust(DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$Cauchy, method = "BH", n = nrow(DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap))

options(ggrepel.max.overlaps = 30)
mycolors <- c("blue", "red", "grey")
names(mycolors) <- c("downregulated", "upregulated", "NS")

DE <- DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap
DE$genesymbol <- rownames(DE)
DE$diffexpressed[DE$avg_log2FC > 0 & DE$BH < 0.05] <- "upregulated"
DE$diffexpressed[DE$avg_log2FC < 0  & DE$BH < 0.05] <- "downregulated"
DE$diffexpressed[DE$BH > 0.05] <- "NS"
DE$delabel <- NA
DE$delabel[DE$diffexpressed != "NS"] <- DE$genesymbol[DE$diffexpressed != "NS"]
DE.DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- DE

ggplot(data = DE.DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap, aes(x = DE.DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_log2FC, 
                                                               y = -log10(DE.DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH), 
                                                               col = diffexpressed, label = delabel)) + geom_point() + theme_minimal() + scale_color_manual(
                                                               values = mycolors) + geom_text_repel()

#Fig. 4C
DefaultAssay(Viremic) <- 'RNA'; Idents(Viremic) <- "HIV_RNA_DNA2"

DEG.Viremic.HIV_RNA_pos_vs_DNA_pos <- FindAllMarkers(object = Viremic, min.pct = 0.15,
                                                     only.pos = TRUE, logfc.threshold = 0.3, pseudocount.use = 1)

DEG.Viremic.HIV_RNA_pos_vs_DNA_pos$BH <- p.adjust(DEG.Viremic.HIV_RNA_pos_vs_DNA_pos$p_val, method = "BH", n = nrow(DEG.Viremic.HIV_RNA_pos_vs_DNA_pos))
DEG.Viremic.HIV_RNA_pos_vs_DNA_pos <- DEG.Viremic.HIV_RNA_pos_vs_DNA_pos[DEG.Viremic.HIV_RNA_pos_vs_DNA_pos$BH < 0.05,]
DEG.Viremic.HIV_RNA_pos_vs_DNA_pos <- DEG.Viremic.HIV_RNA_pos_vs_DNA_pos[!duplicated(DEG.Viremic.HIV_RNA_pos_vs_DNA_pos$gene),]
DEG.Viremic.HIV_RNA_pos_vs_DNA_pos <- DEG.Viremic.HIV_RNA_pos_vs_DNA_pos[DEG.Viremic.HIV_RNA_pos_vs_DNA_pos$cluster != "negative",]
DEG.Viremic.HIV_RNA_pos_vs_DNA_pos50 <- DEG.Viremic.HIV_RNA_pos_vs_DNA_pos %>% group_by(cluster) %>% top_n(n = 50, wt = avg_log2FC)

avg_exp.Viremic <- AverageExpression(Viremic, return.seurat = T, group.by = 'HIV_RNA_DNA2')
avg_exp.Viremic$orig.ident <- colnames(avg_exp.Viremic)
DefaultAssay(avg_exp.Viremic) <- "RNA"
avg_exp.Viremic<- ScaleData(avg_exp.Viremic)

Idents(avg_exp.Viremic) <- "orig.ident"
Idents(avg_exp.Viremic) <- factor(Idents(avg_exp.Viremic), levels = c("HIV RNA and double positive", "HIV DNA positive", "HIV negative"))

DoHeatmap(object = avg_exp.Viremic, features =  DEG.Viremic.HIV_RNA_pos_vs_DNA_pos50$gene, 
          draw.lines = FALSE) + ggtitle("viremic HIV RNA+ vs DNA+ vs HIV- top 50 RNA expression") + scale_fill_gradientn(colors = c("blue", "white", "red"))


#Fig. 4D
Idents(Suppressed) <- "HIV_RNA_DNA2"; Idents(Viremic) <- "HIV_RNA_DNA2"
Idents(Suppressed) <- factor(Idents(Suppressed), levels = c("DNA positive","RNA and double positive", "negative"))
Idents(Viremic) <- factor(Idents(Viremic), levels = c("DNA positive","RNA and double positive", "negative"))

DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg <- DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap[DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$avg_log2FC > 0,]
DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg <- DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg[DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg$BH < 0.05,]
DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg$gene <- rownames(DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg)
rownames(DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg) <- 1:nrow(DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg)
DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg$number  <- rownames(DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg)

DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg <- DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg[
  DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg$number %in% c("5","8","12","26","30","31","33","42","45",
                                                               "48","50","54","55","57","61","62","66","68","72","74","76","79","80","84","89"),]

DotPlot(Viremic, features = DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg$gene, dot.scale = 30, cols = c("grey","blue")) + scale_y_discrete(limits = rev) 
DotPlot(Suppressed, features = DEG.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap_upreg$gene, dot.scale = 30, cols = c("grey","blue")) + scale_y_discrete(limits = rev) 

#Fig. 4E
Idents(Suppressed) <- "HIV_RNA_DNA2"; Idents(Viremic) <- "HIV_RNA_DNA2"
Idents(Suppressed) <- factor(Idents(Suppressed), levels = c("DNA positive","RNA and double positive", "negative"))
Idents(Viremic) <- factor(Idents(Viremic), levels = c("DNA positive","RNA and double positive", "negative"))

DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg <- DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap[DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_log2FC > 0,]
DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg <- DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg[DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$BH < 0.05,]
DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$gene <- rownames(DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg)
rownames(DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg) <- 1:nrow(DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg)
DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$number  <- rownames(DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg)

DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg <- DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg[
  DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$number %in% c("1","2","4","7","8","9","11","12","13","18","25","27",
                                                               "32","34","37","42","44","46","56","58","61","62","64","65","68"),]

DotPlot(Viremic, features = DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$gene, dot.scale = 30, cols = c("grey","blue")) + scale_y_discrete(limits = rev) 
DotPlot(Suppressed, features = DEG.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap_upreg$gene, dot.scale = 30, cols = c("grey","blue")) + scale_y_discrete(limits = rev)

#Fig. 4F
splitcorheatmap(corDNApositive_corHIVnegative, module_RNApos_proliferation, "yDNApos_xHIVneg_module_viremic_WGCNA_proliferation")

#Fig. 4G
splitcorheatmap(corRNA_doublePositive_corHIVnegative, module_RNApos_proliferation, "yRNApos_xHIVneg_module_viremic_WGCNA_proliferation")

#Fig. 4H
DefaultAssay(Viremic) <- "RNA"
all.genes.Viremic <- rownames(GetAssayData(Viremic))

GO.upreg_genes <- module_RNApos_proliferation

GeneList <- ifelse(all.genes.Viremic %in% GO.upreg_genes, 1, 0)
names(GeneList) <- all.genes.Viremic

GO.module_RNApos_proliferation <- new("topGOdata", ontology = "BP", 
                                       allGenes = GeneList, geneSelectionFun = function(x)(x==1), annot = annFUN.org, 
                                       mapping = "org.Hs.eg.db", ID = "symbol")

resultsFisher <- runTest(GO.module_RNApos_proliferation, algorithm = "elim", statistic = "fisher")
GO_table.module_RNApos_proliferation <- GenTable(GO.module_RNApos_proliferation, 
                                                  Fisher = resultsFisher, topNodes = 30, numChar = 100)

GO_table.module_RNApos_proliferation$Fisher <- as.numeric(GO_table.module_RNApos_proliferation$Fisher)
GO_table.module_RNApos_proliferation$value <- (-log10(GO_table.module_RNApos_proliferation$Fisher))
GO_table.module_RNApos_proliferation<-GO_table.module_RNApos_proliferation[order(GO_table.module_RNApos_proliferation$value, decreasing = TRUE),]
GO_table.module_RNApos_proliferation$Term<-factor(GO_table.module_RNApos_proliferation$Term, levels = rev(GO_table.module_RNApos_proliferation$Term))

ggplot(GO_table.module_RNApos_proliferation, aes(y = Term, x = value)) + geom_bar(stat="identity")+theme_classic() + xlab("-log10(Fisher exact P)") + ylab("GO term") 

#Fig. 4I and Fig. 4J
DefaultAssay(Viremic) <- "RNA"; Idents(Viremic) <- "HIV_RNA_DNA2"

Rank_viremic_HIV_RNApos <- FindMarkers(Viremic, ident.1 = "RNA and double positive", only.pos = FALSE, logfc.threshold = 0, min.pct = 0)
GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg <- Rank_viremic_HIV_RNApos$avg_log2FC
names(GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg) <- rownames(Rank_viremic_HIV_RNApos)
fgsea_GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg <- fgsea(pathways = fgsea_sets, 
                                                                stats = GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg,
                                                                eps   = 0.0, minSize=10, maxSize=500, scoreType = "pos")

Rank_viremic_HIV_DNApos <- FindMarkers(Viremic, ident.1 = "DNA positive", only.pos = FALSE, logfc.threshold = 0, min.pct = 0)
GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg <- Rank_viremic_HIV_DNApos$avg_log2FC
names(GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg) <- rownames(Rank_viremic_HIV_DNApos)
fgsea_GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg <- fgsea(pathways = fgsea_sets, 
                                                                stats = GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg,
                                                                eps   = 0.0, minSize=10, maxSize=500, scoreType = "pos")


Rank_viremic_HIV_neg <- FindMarkers(Viremic, ident.1 = "negative", only.pos = FALSE, logfc.threshold = 0, min.pct = 0)
GSEA.DEG.allmarkers.Viremic.HIVneg_vs_HIVpos <- Rank_viremic_HIV_neg$avg_log2FC
names(GSEA.DEG.allmarkers.Viremic.HIVneg_vs_HIVpos) <- rownames(Rank_viremic_HIV_neg)
fgsea_GSEA.DEG.allmarkers.Viremic.HIVneg_vs_HIVpos <- fgsea(pathways = fgsea_sets, 
                                                            stats = GSEA.DEG.allmarkers.Viremic.HIVneg_vs_HIVpos,
                                                            eps   = 0.0, minSize=10, maxSize=500, scoreType = "pos")

NES_viremic_HIV_RNApos_vsDNApos <- merge(fgsea_GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg, fgsea_GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg, by = "pathway")
NES_viremic_HIV_RNApos_vsDNApos$NES_diff <- NES_viremic_HIV_RNApos_vsDNApos$NES.x - NES_viremic_HIV_RNApos_vsDNApos$NES.y
NES_viremic_HIV_RNApos_vsDNApos_RNAUP <- NES_viremic_HIV_RNApos_vsDNApos[NES_viremic_HIV_RNApos_vsDNApos$NES_diff > 0,]
NES_viremic_HIV_RNApos_vsDNApos_DNAUP <- NES_viremic_HIV_RNApos_vsDNApos[NES_viremic_HIV_RNApos_vsDNApos$NES_diff < 0,]
NES_viremic_HIV_RNApos_vsDNApos_RNAUP <- NES_viremic_HIV_RNApos_vsDNApos_RNAUP[NES_viremic_HIV_RNApos_vsDNApos_RNAUP$pval.x < 0.05,]
NES_viremic_HIV_RNApos_vsDNApos_DNAUP <- NES_viremic_HIV_RNApos_vsDNApos_DNAUP[NES_viremic_HIV_RNApos_vsDNApos_DNAUP$pval.y < 0.05,]

p4 <- plotEnrichment(fgsea_sets[["PID_INTEGRIN_CS_PATHWAY"]], 
                     GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg) + labs(title = "PID_INTEGRIN_CS_PATHWAY")
p10 <- plotEnrichment(fgsea_sets[["PID_INTEGRIN_CS_PATHWAY"]], 
                      GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg) + labs(title = "PID_INTEGRIN_CS_PATHWAY")
p16 <- plotEnrichment(fgsea_sets[["PID_INTEGRIN_CS_PATHWAY"]], 
                      GSEA.DEG.allmarkers.Viremic.HIVneg_vs_HIVpos) + labs(title = "PID_INTEGRIN_CS_PATHWAY")

fgsea_GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg[which(fgsea_GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg$pathway == 
                                                               'PID_INTEGRIN_CS_PATHWAY'),]$leadingEdge

ggplot(p4$data, aes(x, y)) + geom_line(color = "red", size = 2) + geom_line(
  data = p10$data, color = "green", size = 2) + labs(title = "PID_INTEGRIN_CS_PATHWAY") + xlab("rank") + ylab("enrichment score") + geom_hline(
    yintercept=0) + geom_vline(xintercept=0) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank()) + geom_line(
    data = p16$data, color = "blue", size = 2)


p7 <- plotEnrichment(fgsea_sets[["HALLMARK_IL6_JAK_STAT3_SIGNALING"]], 
                     GSEA.DEG.allmarkers.Viremic.HIV_RNApos_vs_HIVneg) + labs(title = "HALLMARK_IL6_JAK_STAT3_SIGNALING")
p17 <- plotEnrichment(fgsea_sets[["HALLMARK_IL6_JAK_STAT3_SIGNALING"]], 
                      GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg) + labs(title = "HALLMARK_IL6_JAK_STAT3_SIGNALING")
p27 <- plotEnrichment(fgsea_sets[["HALLMARK_IL6_JAK_STAT3_SIGNALING"]], 
                      GSEA.DEG.allmarkers.Viremic.HIVneg_vs_HIVpos) + labs(title = "HALLMARK_IL6_JAK_STAT3_SIGNALING")

fgsea_GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg[which(fgsea_GSEA.DEG.allmarkers.Viremic.HIV_DNApos_vs_HIVneg$pathway == 
                                                               'HALLMARK_IL6_JAK_STAT3_SIGNALING'),]$leadingEdge

ggplot(p7$data, aes(x, y)) + geom_line(color = "red", size = 2) + geom_line(
  data = p17$data, color = "green", size = 2) + labs(title = "HALLMARK_IL6_JAK_STAT3_SIGNALING") + xlab("rank") + ylab("enrichment score") + geom_hline(
    yintercept=0) + geom_vline(xintercept=0) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank()) + geom_line(
    data = p27$data, color = "blue", size = 2)
