library(Seurat)
library(Signac)
library(ggplot2)
library(cowplot)
library(patchwork)
library(dplyr)
library(qlcMatrix)
library(reshape2)
library(scales)
library(Matrix)
library(WGCNA)
library(flashClust)
library(Hmisc)
library(qlcMatrix)
library(reshape2)
library(scales)
library(Matrix)


#require objects generated by "Preprocessing.R" 
#require processing by "recall ATAC peaks and build motifs.R"
#require processing by "build WGCNA.R"
#require Antibody_stats_Proliferating.csv

#Fig 1A
DimPlot(Combined, reduction = "umap.wnn", group.by = "WNNcelltype", raster = FALSE, label = TRUE) 

#Fig 1B
#Pie charts by table(Combined$Condition, Combined$WNNCelltype)

#Fig 1C
splitcorheatmap(corViremic_corHealthy, module_viremic_WGCNA_proliferation, "yViremic_xHealthy_module_viremic_WGCNA_proliferation") 

#Fig 1D
splitcorheatmap(corSuppressed_corHealthy, module_viremic_WGCNA_proliferation, "ySuppressed_xHealthy_module_viremic_WGCNA_proliferation")

#Fig 1E
DotPlot(Combined, features = c("module_viremic_WGCNA_proliferation"), dot.scale = 10) + ggtitle("module_viremic_WGCNA_proliferation")

#Figure 1F
DefaultAssay(Proliferating.ATAC) <- 'chromvar'; Idents(Proliferating.ATAC) <- "Sample"
DEM.Proliferating.condition <- FindAllMarkers(Proliferating.ATAC,
                                              only.pos = TRUE, min.pct = 0, slot = "data",
                                              logfc.threshold = 0.3, mean.fxn = rowMeans, fc.name = "avg_diff",pseudocount.use = 1)
DEM.Proliferating.condition <- DEM.Proliferating.condition[DEM.Proliferating.condition$pct.1 > DEM.Proliferating.condition$pct.2,]
DEM.Proliferating.condition$BH <- p.adjust(DEM.Proliferating.condition$p_val, 
                                           method = "BH", n = nrow(DEM.Proliferating.condition))
DEM.Proliferating.condition$gene.name <- ConvertMotifID(motif.names, id = DEM.Proliferating.condition$gene)

DEM.Proliferating.condition <- DEM.Proliferating.condition[DEM.Proliferating.condition$BH < 0.05,]
DEM.Proliferating.condition <- DEM.Proliferating.condition[!duplicated(DEM.Proliferating.condition$gene.name),]
DEM.Proliferating.condition<- DEM.Proliferating.condition[order(DEM.Proliferating.condition$gene.name),]
DEM.Proliferating.condition <- DEM.Proliferating.condition[DEM.Proliferating.condition$cluster != 'Healthy',]

DefaultAssay(Proliferating.ATAC) <- 'chromvar'; Idents(Proliferating.ATAC) <- "Condition"
Proliferating.ATAC@assays$chromvar@counts <- Proliferating.ATAC@assays$chromvar@data
avg_exp.Proliferating.ATAC.chromvar <- AverageExpression(Proliferating.ATAC, return.seurat = TRUE,  group.by = 'Condition', assays = "chromvar", slot = "counts")
avg_exp.Proliferating.ATAC.chromvar$orig.ident <- colnames(avg_exp.Proliferating.ATAC.chromvar)
DefaultAssay(avg_exp.Proliferating.ATAC.chromvar) <- "chromvar"
Idents(avg_exp.Proliferating.ATAC.chromvar) <- "orig.ident"

DoHeatmap(object = avg_exp.Proliferating.ATAC.chromvar, features = DEM.Proliferating.condition$gene, slot = "counts",
          draw.lines = FALSE)  + scale_y_discrete(labels = rev(DEM.Proliferating.condition$gene.name)) + scale_fill_gradientn(colors = c("blue", "white", "red"))

#Figure 1G
DefaultAssay(Proliferating) <- "RNA"; Idents(Proliferating) <- "Condition"

DEG.Proliferating.Condition <- FindAllMarkers(object = Proliferating, only.pos = TRUE, min.pct = 0.1,
                                           logfc.threshold = 0.25, test.use = "wilcox", pseudocount.use = 1)
DEG.Proliferating.Condition$BH <- p.adjust(DEG.Proliferating.Condition$p_val, method = "BH", n = nrow(DEG.Proliferating.Condition))
DEG.Proliferating.Condition <- DEG.Proliferating.Condition[DEG.Proliferating.Condition$BH < 0.05,]
DEG.Proliferating.Condition <- DEG.Proliferating.Condition[!duplicated(DEG.Proliferating.Condition$gene),]
DEG.Proliferating.Condition <- DEG.Proliferating.Condition[!grepl('MT', DEG.Proliferating.Condition$gene),]
DEG.Proliferating.Condition <- DEG.Proliferating.Condition[!grepl('RPL', DEG.Proliferating.Condition$gene),]
DEG.Proliferating.Condition <- DEG.Proliferating.Condition[!grepl('RPS', DEG.Proliferating.Condition$gene),]
DEG.Proliferating.Condition <- DEG.Proliferating.Condition[DEG.Proliferating.Condition$cluster != "Healthy",]
DEG.Proliferating.Condition_top50 <- DEG.Proliferating.Condition %>% group_by(cluster) %>% top_n(n = 50, wt = avg_log2FC)

avg_exp.Proliferating.RNA <- AverageExpression(Proliferating.RNA, return.seurat = T, group.by = 'Sample')
avg_exp.Proliferating.RNA$orig.ident <- colnames(avg_exp.Proliferating.RNA)
DefaultAssay(avg_exp.Proliferating.RNA) <- "RNA"
Idents(avg_exp.Proliferating.RNA) <- "orig.ident"
avg_exp.Proliferating.RNA<- ScaleData(avg_exp.Proliferating.RNA)

DoHeatmap(object = avg_exp.Proliferating.RNA, features = DEG.Proliferating.Condition_top50$gene, 
          draw.lines = FALSE) + scale_fill_gradientn(colors = c("blue", "white", "red"))

#Fig 1H
Antibody_stats_Proliferating <- data.frame(antibody = Proliferating.cite[["Antibody"]]@data)
Antibody_stats_Proliferating$mean <- rowMeans(Antibody_stats_Proliferating, na.rm=TRUE)
Antibody_stats_Proliferating$sd <- apply(Antibody_stats_Proliferating, 1, sd, na.rm=TRUE)
Antibody_stats_Proliferating$names <- rownames(Antibody_stats_Proliferating)
Antibody_stats_Proliferating <- Antibody_stats_Proliferating[,c(2728, 2729, 2730)]
#match  each row of protein rows with its specific isotype control (using e.g., excel; required columns are protein and standard deviations and mean expressions) then compute 2 sample z score

Antibody_stats_Proliferating$X2.sample.z.score <- (Antibody_stats_Proliferating$mean - 
                                      Antibody_stats_Proliferating$isotype_mean)/sqrt(Antibody_stats_Proliferating$sd^2/2727 +
                                      Antibody_stats_Proliferating$isotype_sd^2/2727)
Antibody_stats_Proliferating <- Antibody_stats_Proliferating[Antibody_stats_Proliferating$X2.sample.z.score > 2,]
rownames(Antibody_stats_Proliferating) <- Antibody_stats_Proliferating$names
#see Antibody_stats_Proliferating.txt

Idents(Proliferating) <- "Condition"

DEA.Proliferating.Condition  <- FindAllMarkers(object = Proliferating.cite, min.pct = 0.15,
                                            only.pos = TRUE, test.use = 'wilcox', features = rownames(Antibody_stats_Proliferating),pseudocount.use = 1)
DEA.Proliferating.Condition <- DEA.Proliferating.Condition[DEA.Proliferating.Condition$pct.1 > DEA.Proliferating.Condition$pct.2,]
DEA.Proliferating.Condition$BH <- p.adjust(DEA.Proliferating.Condition$p_val, 
                                        method = "BH", n = nrow(DEA.Proliferating.Condition))
DEA.Proliferating.Condition <- DEA.Proliferating.Condition[DEA.Proliferating.Condition$BH < 0.05,]
DEA.Proliferating.Condition <- DEA.Proliferating.Condition %>% group_by(cluster)

avg_exp.Proliferating <- AverageExpression(Proliferating, return.seurat = T, group.by = 'Condition')
avg_exp.Proliferating$orig.ident <- colnames(avg_exp.Proliferating)
Idents(avg_exp.Proliferating) <- "orig.ident"
avg_exp.Proliferating <- ScaleData(avg_exp.Proliferating)
Idents(avg_exp.Proliferating) <- factor(Idents(avg_exp.Proliferating), levels = c("Viremic", "Suppressed", "Healthy"))

DoHeatmap(object = avg_exp.Proliferating, features = DEA.Proliferating.Condition$gene, group.bar.height = 0.02, size = 4, angle = 0, 
          draw.lines = FALSE) + scale_fill_gradientn(colors = c("blue", "white", "red"))

#Fig 1I
DefaultAssay(Proliferating.ATAC) <- "ATAC"
CoveragePlot(Proliferating.ATAC, region = "IKZF3", ranges = StringToGRanges("chr17-39769657-39770628"))
CoveragePlot(Proliferating.ATAC, region = "chr17-35870000-35893000", ranges = StringToGRanges("chr17-35879803-35880648"))
CoveragePlot(Proliferating.ATAC, region = "chr17-35870000-35893000", ranges = StringToGRanges("chr17-35890410-35891607"))
CoveragePlot(Proliferating.ATAC, region = "IFI16", ranges = StringToGRanges("chr1-159012494-159012845"))
CoveragePlot(Proliferating.ATAC, region = "chr12-68150000-68163000", ranges = StringToGRanges("chr12-68159262-68160105"))
CoveragePlot(Proliferating.ATAC, region = "IL2RB", ranges = StringToGRanges("chr22-37162217-37163074"))

#Fig 1J
ggplot(data.frame(IKZF3 = Proliferating[["RNA"]]@data["IKZF3",], cluster = Proliferating$Condition), 
       aes(x = cluster, y = IKZF3)) + geom_violin(aes(fill = cluster), trim=FALSE, scale = "width") + ggtitle("Proliferating IKZF3 RNA expression")
ggplot(data.frame(CCL5 = Proliferating[["RNA"]]@data["CCL5",], cluster = Proliferating$Condition), 
       aes(x = cluster, y = CCL5)) + geom_violin(aes(fill = cluster), trim=FALSE, scale = "width") + ggtitle("proliferating CCL5 RNA expression")
ggplot(data.frame(IFI16 = Proliferating[["RNA"]]@data["IFI16",], cluster = Proliferating$Condition), 
       aes(x = cluster, y = IFI16)) + geom_violin(aes(fill = cluster), trim=FALSE, scale = "width") + ggtitle("proliferating IFI16 RNA expression")
ggplot(data.frame(IFNG = Proliferating[["RNA"]]@data["IFNG",], cluster = Proliferating$Condition), 
       aes(x = cluster, y = IFNG)) + geom_violin(aes(fill = cluster), trim=FALSE, scale = "width") + ggtitle("proliferating IFNG RNA expression")
ggplot(data.frame(IL2RB = Proliferating[["RNA"]]@data["IL2RB",], cluster = Proliferating$Condition), 
       aes(x = cluster, y = IL2RB)) + geom_violin(aes(fill = cluster), trim=FALSE, scale = "width") + ggtitle("proliferating IL2RB RNA expression")


