library(Seurat)
library(Signac)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(patchwork)
library(dplyr)
library(abind)
library(ACAT)


#require objects generated by "Preprocessing.R" 
#require processing by "ATAC peaks recall and motif analyses build"

#Fig. 3A
DimPlot(Viremic, reduction = "umap.wnn", group.by = "HIV_RNA_DNA", 
        pt.size = 0.8, cols= c("light grey", "blue", "green", "red"), 
        order = c("double positive", "DNA positive", "RNA positive", "negative"), raster=FALSE) + ggtitle("Viremic HIV RNA+ and DNA+")

#Fig. 3B
DimPlot(Suppressed, reduction = "umap.wnn", group.by = "HIV_RNA_DNA", 
        pt.size = 0.8, cols= c("light grey", "blue", "green", "red"), 
        order = c("double positive", "DNA positive", "RNA positive", "negative"), raster=FALSE) + ggtitle("Suppressed HIV RNA+ and DNA+")

#Fig. 3C
#Pie charts by table(Viremic$WNNCelltype, Viremic$HIV_RNA_DNA)
#Pie charts by table(Suppressed$WNNCelltype, Suppressed$HIV_RNA_DNA)
#Pie charts by table(Uninfected$WNNCelltype, Uninfected$HIV_RNA_DNA)

#Fig. 3D
DefaultAssay(Viremic.ATAC) <- 'chromvar'
Idents(Viremic.ATAC) <- "HIV_RNA_DNA"

DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg <- vector(mode = "list", length = 1000)
DEM.downsample.HIV_DNA_Pos_vs_Neg_bootstrap <- vector(mode = "list", length = 1000)
for(i in 1:length(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg)){
  DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- FindMarkers(object = Viremic.ATAC, ident.1 = "DNA positive", ident.2 = "negative", min.pct = 0, logfc.threshold = 0.2, 
                                                                max.cells.per.ident = 233, random.seed = i, only.pos = FALSE, mean.fxn = rowMeans, fc.name = "avg_diff", pseudocount.use = 1)
  DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]]$BH <- p.adjust(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]]$p_val, 
                                                                method = "BH", n = nrow(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]]))
  merged_ID <- unique(c(rownames(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]])))
  DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]][merged_ID,]
  DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]] <- DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]][order(rownames(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]])),]
  DEM.downsample.HIV_DNA_Pos_vs_Neg_bootstrap[[i]] <- data.frame(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[i]][,1])
  downsample.HIV_RNA_Pos_vs_Neg_bootstrap1 <- t(matrix(unlist(DEM.downsample.HIV_DNA_Pos_vs_Neg_bootstrap), nrow = length(merged_ID)))
  Cauchy <- ACAT(matrix(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1, ncol = ncol(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1)))
  matrix <- cbind(DEM.Viremic.downsample.HIV_DNA_Pos_vs_Neg[[1]], Cauchy)
  DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- matrix[, -c(1,5,6)]
}
DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH <- p.adjust(DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$Cauchy, method = "BH", n = nrow(DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap))
DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$motifname <-rownames(DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap)
DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$gene <- ConvertMotifID(motif.names, id = rownames(DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap))

options(ggrepel.max.overlaps = 30)
mycolors <- c("blue", "red", "grey")
names(mycolors) <- c("downregulated", "upregulated", "NS")

DE <- DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap
DE$genesymbol <- DE$gene
DE$diffexpressed[DE$avg_diff > 0 & DE$BH < 0.05] <- "upregulated"
DE$diffexpressed[DE$avg_diff < 0  & DE$BH < 0.05] <- "downregulated"
DE$diffexpressed[DE$BH > 0.05] <- "NS"
DE$delabel <- NA
DE$delabel[DE$diffexpressed != "NS"] <- DE$genesymbol[DE$diffexpressed != "NS"]
DE.DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap <- DE

ggplot(data = DE.DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap, aes(x = DE.DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$avg_diff, 
                                          y = -log10(DE.DEM.Viremic.HIV_DNA_Pos_vs_Neg_bootstrap$BH), 
                                          col = diffexpressed, label = delabel)) + geom_point() + theme_minimal() + scale_color_manual(
                                          values = mycolors) + geom_text_repel() 

#Fig. 3E
DefaultAssay(Viremic.ATAC) <- 'chromvar'
Idents(Viremic.ATAC) <- "HIV_RNA_DNA"

DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg <- vector(mode = "list", length = 1000)
DEM.downsample.HIV_RNA_Pos_vs_Neg_bootstrap <- vector(mode = "list", length = 1000)
for(i in 1:length(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg)){
  DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- FindMarkers(object = Viremic.ATAC, ident.1 = c("positive_positive", "positive_negative"), ident.2 = "negative_negative", min.pct = 0, logfc.threshold = 0.2, 
                                                                max.cells.per.ident = 256, random.seed = i, only.pos = FALSE, mean.fxn = rowMeans, fc.name = "avg_diff", pseudocount.use = 1)
  DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]]$BH <- p.adjust(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]]$p_val, 
                                                                method = "BH", n = nrow(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]]))
  merged_ID <- unique(c(rownames(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]])))
  DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]][merged_ID,]
  DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]] <- DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]][order(rownames(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]])),]
  DEM.downsample.HIV_RNA_Pos_vs_Neg_bootstrap[[i]] <- data.frame(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[i]][,1])
  downsample.HIV_RNA_Pos_vs_Neg_bootstrap1 <- t(matrix(unlist(DEM.downsample.HIV_RNA_Pos_vs_Neg_bootstrap), nrow = length(merged_ID)))
  Cauchy <- ACAT(matrix(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1, ncol = ncol(downsample.HIV_RNA_Pos_vs_Neg_bootstrap1)))
  matrix <- cbind(DEM.Viremic.downsample.HIV_RNA_Pos_vs_Neg[[1]], Cauchy)
  DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- matrix[, -c(1,5,6)]
}
DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH <- p.adjust(DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$Cauchy, method = "BH", n = nrow(DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap))
DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$motifname <-rownames(DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap)
DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$gene <- ConvertMotifID(motif.names, id = rownames(DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap))

options(ggrepel.max.overlaps = 30)
mycolors <- c("blue", "red", "grey")
names(mycolors) <- c("downregulated", "upregulated", "NS")

DE <- DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap
DE$genesymbol <- DE$gene
DE$diffexpressed[DE$avg_diff > 0 & DE$BH < 0.05] <- "upregulated"
DE$diffexpressed[DE$avg_diff < 0  & DE$BH < 0.05] <- "downregulated"
DE$diffexpressed[DE$BH > 0.05] <- "NS"
DE$delabel <- NA
DE$delabel[DE$diffexpressed != "NS"] <- DE$genesymbol[DE$diffexpressed != "NS"]
DE.DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap <- DE

ggplot(data = DE.DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap, aes(x = DE.DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$avg_diff, 
                                                               y = -log10(DE.DEM.Viremic.HIV_RNA_Pos_vs_Neg_bootstrap$BH), 
                                                               col = diffexpressed, label = delabel)) + geom_point() + theme_minimal() + scale_color_manual(
                                                                 values = mycolors) + geom_text_repel() 

#Fig. 3F
Viremic.ATAC$HIV_RNA_DNA2 <- Viremic.ATAC$HIV_RNA_DNA
Idents(Viremic.ATAC) <- "HIV_RNA_DNA2"
Viremic.ATAC <-RenameIdents(Viremic.ATAC, 'positive_positive' = 'HIV RNA and double positive', 
                            'positive_negative' = 'HIV RNA and double positive', 'negative_positive' = 'HIV DNA positive',
                            'negative_negative' = 'HIV negative') 
Viremic.ATAC$HIV_RNA_DNA2 <- Idents(Viremic.ATAC)
DefaultAssay(Viremic.ATAC) <- "chromvar"; Idents(Viremic.ATAC) <- "HIV_RNA_DNA2"

DEM.Viremic.HIV_RNA_pos_vs_DNA_pos <- FindAllMarkers(object = Viremic.ATAC,  min.pct = 0,
                                                     only.pos = TRUE, logfc.threshold = 0.2, mean.fxn = rowMeans, fc.name = "avg_diff", pseudocount.use = 1)
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$BH <- p.adjust(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$p_val, method = "BH", n = nrow(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos))
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$gene <- ConvertMotifID(motif.names, id = rownames(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos))
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos <- DEM.Viremic.HIV_RNA_pos_vs_DNA_pos[DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$BH < 0.05,]
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos<- DEM.Viremic.HIV_RNA_pos_vs_DNA_pos[order(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$avg_diff),]
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos<- DEM.Viremic.HIV_RNA_pos_vs_DNA_pos[order(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$cluster),]
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos <- DEM.Viremic.HIV_RNA_pos_vs_DNA_pos[DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$cluster != 'negative',]
DEM.Viremic.HIV_RNA_pos_vs_DNA_pos <- DEM.Viremic.HIV_RNA_pos_vs_DNA_pos[! is.na(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$gene),]

Viremic.ATAC@assays$chromvar@counts <- Viremic.ATAC@assays$chromvar@data
avg_exp.Viremic.ATAC.chromvar <- AverageExpression(Viremic.ATAC, return.seurat = TRUE, group.by = 'HIV_RNA_DNA2', assays = "chromvar", slot = "counts")
avg_exp.Viremic.ATAC.chromvar$orig.ident <- colnames(avg_exp.Viremic.ATAC.chromvar)
DefaultAssay(avg_exp.Viremic.ATAC.chromvar) <- "chromvar"; Idents(avg_exp.Viremic.ATAC.chromvar) <- "orig.ident"
Idents(avg_exp.Viremic.ATAC.chromvar) <- factor(Idents(avg_exp.Viremic.ATAC.chromvar), levels = c("HIV DNA positive", "HIV RNA and double positive", "HIV negative"))

DoHeatmap(object = avg_exp.Viremic.ATAC.chromvar, features = rev(rownames(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos)), slot = "counts",
          draw.lines = FALSE) + scale_y_discrete(labels = c(DEM.Viremic.HIV_RNA_pos_vs_DNA_pos$gene)) + scale_fill_gradientn(colors = c("blue", "white", "red"))
